apiVersion: v1
kind: Secret
metadata:
  name: vault-reviewer-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: vault-reviewer
type: kubernetes.io/service-account-token
